# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  ImGui_config = debug
  GLFW_config = debug
  Glad_config = debug
  Walnut_config = debug
  WalnutApp_config = debug

else ifeq ($(config),release)
  ImGui_config = release
  GLFW_config = release
  Glad_config = release
  Walnut_config = release
  WalnutApp_config = release

else ifeq ($(config),dist)
  ImGui_config = dist
  GLFW_config = dist
  Glad_config = dist
  Walnut_config = dist
  WalnutApp_config = dist

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := ImGui GLFW Glad Walnut WalnutApp

.PHONY: all clean help $(PROJECTS) Core Dependencies

all: $(PROJECTS)

Core: Walnut

Dependencies: GLFW Glad ImGui

ImGui:
ifneq (,$(ImGui_config))
	@echo "==== Building ImGui ($(ImGui_config)) ===="
	@${MAKE} --no-print-directory -C vendor/imgui -f Makefile config=$(ImGui_config)
endif

GLFW:
ifneq (,$(GLFW_config))
	@echo "==== Building GLFW ($(GLFW_config)) ===="
	@${MAKE} --no-print-directory -C vendor/glfw -f Makefile config=$(GLFW_config)
endif

Glad:
ifneq (,$(Glad_config))
	@echo "==== Building Glad ($(Glad_config)) ===="
	@${MAKE} --no-print-directory -C vendor/glad -f Makefile config=$(Glad_config)
endif

Walnut: ImGui GLFW
ifneq (,$(Walnut_config))
	@echo "==== Building Walnut ($(Walnut_config)) ===="
	@${MAKE} --no-print-directory -C Walnut -f Makefile config=$(Walnut_config)
endif

WalnutApp: Walnut
ifneq (,$(WalnutApp_config))
	@echo "==== Building WalnutApp ($(WalnutApp_config)) ===="
	@${MAKE} --no-print-directory -C WalnutApp -f Makefile config=$(WalnutApp_config)
endif

clean:
	@${MAKE} --no-print-directory -C vendor/imgui -f Makefile clean
	@${MAKE} --no-print-directory -C vendor/glfw -f Makefile clean
	@${MAKE} --no-print-directory -C vendor/glad -f Makefile clean
	@${MAKE} --no-print-directory -C Walnut -f Makefile clean
	@${MAKE} --no-print-directory -C WalnutApp -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  dist"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   ImGui"
	@echo "   GLFW"
	@echo "   Glad"
	@echo "   Walnut"
	@echo "   WalnutApp"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"